name: Lint remote javascript

on:
  schedule:
    # Every thursday at 00:00
    - cron: '0 0 * * THU'
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.11
    - run: yarn install
    - run: yarn build
    - run: yarn install --no-lockfile
      working-directory: ./ci
    - run: yarn lint:javascript
      working-directory: ./ci
      env:
        CI: true