name: Lint remote typescript

on: [workflow_dispatch]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.11
    - run: yarn install
    - run: yarn build
    - run: node dist --config configs/eslint-remote-tester.typescript.config.js
      env:
        CI: true